name: qld_covid_map
description: A new Flutter project.

publish_to: 'none'

version: 0.0.2+2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  # Visual dependencies
  # For making the main exposures table
  syncfusion_flutter_datagrid: ^19.4.38
  syncfusion_flutter_maps: 19.4.38-beta

  # Opening the url for the link
  url_launcher: ^6.0.17

  # For formatting dates
  intl: ^0.17.0

  # For loading scraped data
  http: ^0.13.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true